baseurl = ""
title = "Marc Nützel"
theme = "hugo-theme"
languageCode = "de-de"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-94002707-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
DefaultContentLanguage = "de"

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/bg.jpg"
  SEOTitle = "Marc Nützel"
  description = "Marc Nützel, Software Entwicklung, Programming, Java, coding"
  keyword = "Marc Nützel, Software Entwicklung, Programming, Java, codi"
  slogan = "just coding"

  image_404 = "img/404-bg.jpg"
  title_404 = "placeholder 404"

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Entwickler, Lösungsfinder und Abenteurer"
  sidebar_avatar = "img/avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  # Baidu Analytics
  ba_track_id = ""

  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  #wechat pay & alipay
  reward = false
  # reward_guide = "如果这篇文章对你有用，请随意打赏"

  [params.social]
  rss            = true
  email          = "me@marc-nuetzel.de"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/marcnuetzel/"
  xing           = "https://www.xing.com/profile/Marc_Nuetzel/"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/heyimMarc"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"

  [[params.friend_link]]
  title = "Nathalie Pechan"
  href =  "http://nathaliepechan.penue.de"

  [[params.bookmark_link]]
  title =  "DB Schenker AG"
  href =  "https://www.dbschenker.com/"
  [[params.bookmark_link]]
  title = "Plus.de"
  href =  "https://www.plus.de"
  [[params.bookmark_link]]
  title = "Gartenxxl.de"
  href =  "https://www.gartenxxl.de"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
